### ISSUE TITLE
Issue saving compressed files

### ISSUE THREAD

**Issue by alexanderwilkinson** [bardiir/caesium#1]
Wonderful to have the Docker instance of this - thank you! 

When running the command caesiumclt -q 30 -o test1 test1.jpg, I get the expected output 

(1/1) test1.jpg -> /test1.jpg
2.88 MB -> 2.73 MB [-5.24%]

but no files are saved.  I've tried multiple variations of same but to no avail.  I don't suppose you know what might be causing the problem?

**Comment by alexanderwilkinson** [comment]
Resolved using some tweaks to the dockerfile you created...  (I suspect the real culprit was a bug in the Caesium code).

FROM alpine:3.6

RUN	buildDeps="git \
	make \
	bash \
	autoconf \
	nasm \
	g++ \
	automake \
	libtool \
	libjpeg-turbo-dev \
	linux-headers \
	cmake \
	sudo" && \
	apk add --no-cache --update ${buildDeps} && \
	apk add libstdc++ libjpeg-turbo && \
	git clone https://github.com/google/zopfli.git && \
	cd zopfli && \
	make libzopflipng && \
	cp libzopflipng.so.1.0.2 /usr/lib && \
	ln -s libzopflipng.so.1.0.2 /usr/lib/libzopflipng.so && \
	ln -s libzopflipng.so.1.0.2 /usr/lib/libzopflipng.so.1 && \
	mkdir /usr/include/zopflipng && \
	cp src/zopflipng/zopflipng_lib.h /usr/include/zopflipng && \
	cd .. && \
	git clone https://github.com/Lymphatus/libcaesium.git && \
	cd libcaesium && \
	mkdir build && \
	cd build && \
	cmake .. && \
	make && \
	sudo make install && \
	git clone https://github.com/Lymphatus/caesium-clt.git && \
	cd caesium-clt && \
	mkdir build && \
	cd build && \
	cmake .. && \
	make && \
	sudo make install && \
	rm -rf /libcaesium && \
	apk del ${buildDeps} && \
	rm -rf /var/cache/apk/*
	
WORKDIR /caesium

**Comment by bardiir** [comment]
This is an issue with caesiumclt which seems to have been fixed, the container on docker hub is just still carrying the old version. I'll update that then the issue should be fixed for the container too. I'm also going to adopt the version update to zopfli.

**Comment by bardiir** [comment]
The original bug reference is here: https://github.com/Lymphatus/caesium-clt/issues/26
